---
- name: Add rancher chart repo to helm
  shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
    HTTPS_PROXY: "{{ rancher_https_proxy }}"
  register: output_results

- debug:
    msg: "{{ output_results.stdout_lines }}"

- name: Ensure dir for rancher chart exists
  file:
    dest: "{{ rancher_chart_dir }}"
    state: directory
    mode: 0755

- name: Download rancher chart
  shell: "helm fetch rancher-stable/rancher --untar --untardir {{ rancher_chart_dir }}"
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
    HTTPS_PROXY: "{{ rancher_https_proxy }}"

- name: Deploy rancher to rancher k8s cluster via helm
  shell: helm upgrade -i rancher rancher --namespace cattle-system --set hostname={{ rancher_ingress_url }} --set ingress.tls.source=secret --set rancherImageTag={{rancher_version}}
  args:
    chdir: "{{ rancher_chart_dir }}"
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: output_results

- debug:
    msg: "{{ output_results.stdout_lines }}"

- name: Verify Rancher successfully deployed to rancher k8s cluster
  shell: kubectl -n cattle-system get po --no-headers |grep -i rancher |grep -i running |wc -l
  ignore_errors: yes
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: verify_rancher_install_result
  until: verify_rancher_install_result.stdout is search( rancher_host_list | length | string )
  retries: 100
  delay: 3

