---
  
- name: Run helm CMD to install rancher chart repo
  command: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: output_results

- debug:
    msg: "{{ output_results.stdout_lines }}"

# - name: Wait until tiller pod is running
#   shell: kubectl -n kube-system get po |grep tiller |grep -i running
#   register: tiller_running_check_result
#   until: tiller_running_check_result.rc == 0
#   retries: 20
#   delay: 1


# - name: Run helm CMD to install certmanager
#   command: helm install stable/cert-manager --name cert-manager --namespace kube-system
#   environment:
#     KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
#   register: output_results

# - debug:
#     msg: "{{ output_results.stdout_lines }}"

    
# ## Allow time for cert mananger to come up (change to poll status!)
# - pause:
#     minutes: 2

- name: Run helm CMD to install rancher-server
  command: helm install rancher-stable/rancher --name rancher --namespace cattle-system --set hostname={{ rancher_ingress_url }} --set ingress.tls.source=secret --set rancherImageTag={{rancher_version}}
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: output_results

- debug:
    msg: "{{ output_results.stdout_lines }}"

    
# ## Allow time for rancher-server to come up (change to poll status!)
# - pause:
#     minutes: 2

# - name: Run kubectl CMD to install tls secrets
#   command: kubectl -n cattle-system create secret tls tls-rancher-ingress --cert="{{ rancher_rke_dir }}/roles/rancher/files/foxsportswildcard.crt" --key="{{ rancher_rke_dir }}/roles/rancher/files/foxsportswildcard.key"
#   environment:
#     KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
#   register: output_results

# - debug:
#     msg: "{{ output_results.stdout_lines }}"
