---
- name: Add rancher chart repo to helm
  shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: output_results

- debug:
    msg: "{{ output_results.stdout_lines }}"

- name: Deploy rancher to rancher k8s cluster via helm
  shell: helm upgrade -i rancher rancher-stable/rancher  --namespace cattle-system --set hostname={{ rancher_ingress_url }} --set ingress.tls.source=secret --set rancherImageTag={{rancher_version}}
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: output_results

- debug:
    msg: "{{ output_results.stdout_lines }}"

- name: Verify Rancher successfully deployed to rancher k8s cluster
  shell: kubectl -n cattle-system get po --no-headers |grep -i rancher |grep -i running |wc -l
  ignore_errors: yes
  environment:
    KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
  register: verify_rancher_install_result
  until: verify_rancher_install_result.stdout is search( rancher_host_list | length | string )
  retries: 100
  delay: 3


# - name: Run kubectl CMD to install tls secrets
#   shell: kubectl -n cattle-system create secret tls tls-rancher-ingress --cert="{{ rancher_rke_dir }}/roles/rancher/files/foxsportswildcard.crt" --key="{{ rancher_rke_dir }}/roles/rancher/files/foxsportswildcard.key"
#   environment:
#     KUBECONFIG: "{{ rancher_kubeconfig_fullpath }}"
#   register: output_results

# - debug:
#     msg: "{{ output_results.stdout_lines }}"
