---
- name: cleanup_rke_private_key
  file:
    dest: "{{ rancher_rke_ssh_private_key_fullpath }}"
    state: absent

- name: cleanup_rancher_cert
  file:
    dest: "{{ rancher_cert_fullpath }}"
    state: absent

- name: cleanup_rancher_cert_key
  file:
    dest: "{{ rancher_cert_key_fullpath }}"
    state: absent